### ISSUE TITLE
align to new README template

### ISSUE THREAD

**Issue by ejaronne** [mitre/oracle-mysql-ee-5.7-cis-baseline#1]
(updated baseline readme link:)
https://github.com/mitre/docs-mitre-inspec/blob/master/templates/baseline_readme.md

Please look into aligning the README.md to the style of the above template, for baseline InSpec profiles.

See examples in the baseline Windows 2012, IIS, and MS SQL baseline profiles.

Thanks! - Eugene.

**Comment by HackerShark** [comment]
Add updated instructions showing command for running profile on windows target using winrm and linux target using ssh since MySQL can run on both.

ex. Windows:  
```inspec exec https://github.com/mitre/Oracle-MySQL-Enterprise-Edition-5.7-cis-baseline/archive/master.tar.gz -t winrm://<hostip> --user '<admin-account>' --password=<password> --reporter cli json:<filename>.json```

ex. Linux:  
```inspec exec https://github.com/mitre/Oracle-MySQL-Enterprise-Edition-5.7-cis-baseline/archive/master.tar.gz -t ssh://<hostip> --user '<admin-account>' --password=<password> --reporter cli json:<filename>.json```

**Comment by ejaronne** [comment]
fixed with https://github.com/mitre/oracle-mysql-ee-5.7-cis-baseline/pull/11
