### ISSUE TITLE
Needs NIST 800-53 Tags

### ISSUE THREAD

**Issue by ejaronne** [mitre/oracle-mysql-ee-5.7-cis-baseline#2]
See the attached to create NIST 800-53 tags based on CIS controls
[NIST80053_to_CIS_SC6.1_Mapping_September2017.xlsx](https://github.com/mitre/Oracle-MySQL-Enterprise-Edition-5.7-cis-baseline/files/3030598/NIST80053_to_CIS_SC6.1_Mapping_September2017.xlsx)

**Comment by asturtevant** [comment]
I'll add these in tomorrow

**Comment by ejaronne** [comment]
Please update the 800-53 control selection for these control IDs
Test ID | New 800-53 # | Reason
-- | -- | --
1.1 | ["SC-2", "Rev_4"] | Application partitioning is better   suited control
1.4 | ["IA-5", "Rev_4"] | Change from IA-5(5) to more general   IA-5 has a statement "Protecting authenticator content from unauthorized   disclosure and modification"
3.1 | ["AC-3", "Rev_4"] | Change CM-5 (6) to the more general   AC-3, access enforcement. CMS-5(6) is not typically a control selected by   agencies.
3.2 | ["AC-3", "Rev_4"] | Change CM-5 (6) to the more general   AC-3, access enforcement. CMS-5(6) is not typically a control selected by   agencies.
3.7 | ["AC-3", "Rev_4"] | Change AC-6, least privilege to AC-3,   access enforcement better suited for file permissions.
3.8 | ["AC-3", "Rev_4"] | Change CM-5 (6) to the more general   AC-3, access enforcement. CMS-5(6) is not typically a control selected by   agencies.
9.1 | ["SC-8", "Rev_4"] | SC-8 is sufficient. SC-8(2) is not   typically selected as a baseline control
